// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pairwise_distances_cpp
arma::mat pairwise_distances_cpp(const arma::mat& M);
RcppExport SEXP _manifoldhrf_pairwise_distances_cpp(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_distances_cpp(M));
    return rcpp_result_gen;
END_RCPP
}
// knn_search_cpp
Rcpp::List knn_search_cpp(const arma::mat& data, const arma::mat& query, int k);
RcppExport SEXP _manifoldhrf_knn_search_cpp(SEXP dataSEXP, SEXP querySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_search_cpp(data, query, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_manifoldhrf_pairwise_distances_cpp", (DL_FUNC) &_manifoldhrf_pairwise_distances_cpp, 1},
    {"_manifoldhrf_knn_search_cpp", (DL_FUNC) &_manifoldhrf_knn_search_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_manifoldhrf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
