# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairwise_distances_cpp <- function(M) {
    .Call(`_manifoldhrf_pairwise_distances_cpp`, M)
}

knn_search_cpp <- function(data, query, k) {
    .Call(`_manifoldhrf_knn_search_cpp`, data, query, k)
}

