# Generated by Rcpp::compileAttributes
# Do not edit by hand

pairwise_distances_cpp <- function(M) {
    .Call(`_manifoldhrf_pairwise_distances_cpp`, M)
}

knn_search_cpp <- function(data, query, k) {
    .Call(`_manifoldhrf_knn_search_cpp`, data, query, k)
}
