name: coverage
on: [push, pull_request]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
      - name: Install covr
        run: install.packages('covr')
      - name: Run coverage and enforce threshold
        run: |
          Rscript -e "cov <- covr::package_coverage(); pct <- covr::percent_coverage(cov); if (pct < 95) stop(sprintf('Coverage (%.2f%%) below threshold', pct));"
      - name: Upload coverage to Codecov
        run: Rscript -e "covr::codecov()"