name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  R-CMD-check:
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, r: '4.2', bioc: 'false'}
          - {os: macOS-latest, r: '4.2', bioc: 'false'}
          - {os: windows-latest, r: '4.2', bioc: 'false'}
          - {os: ubuntu-latest, r: 'devel', bioc: 'true'}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/cache@v2
        with:
          path: ${{ runner.os }}-pak
          key: ${{ runner.os }}-pak-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-pak-
      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
      - name: Build package
        run: R CMD build .
      - name: Check package
        run: R CMD check --no-manual --as-cran *.tar.gz